NIL = "nil"
BYTES_TYPE_AS_STRING = "<class 'bytes'>"
UTF8_CONSTANT = "utf-8"

STATE_PREFIX = "state"
TRANSITION_PREFIX = "transition"
INITIAL_PREFIX = "intial"
FINAL_PREFIX = "final"
ALIAS_PREFIX = "alias"
SUPERSTATE_PREFIX = "substate"
REGION_PREFIX = "region"
ENTRY_PSEUDOSTATE_PREFIX = "entry_pseudostate"
CHOICE_STATE_PREFIX = "choice"
JUNCTION_STATE_PREFIX = "junction"
EXIT_PSEUDOSTATE_PREFIX = "exit_pseudostate"
ON_ENTRY_ACTION_PREFIX = "on_entry_action"
DO_ACTION_PREFIX = "do_action"
ON_EXIT_ACTION_PREFIX = "on_exit_action"
EVENT_PREFIX = "event"
ACTION_PREFIX = "action"
PROCEDURE_PREFIX = "proc"
INTERNAL_TRANSITION_PREFIX = "internal_transition"

