@startuml


s31  --->  active_exit : / b'beep();'
s71  --->  configuring : / b"echo('Configuring mode');"
activated  --->  s11 : reset / log b"ABORT 'Make Siren Sound'"
reading  --->  s71 : set / log b"ABORT 'Slow blinking red LED'"
s11  --->  s12 : / b"echo('Exit Emergency');"
configuring  --->  configuring : done [b'tThreshold <= tCurrent'] / b'generateError();'
activated  --->  s21 : deactivate / log b"ABORT 'Make Siren Sound'"
configuring  --->  configuring : set tThreshold / b'doubleBeep();'
reading  --->  s91 : when b'tCurrent >= tThreshold' / log b"ABORT 'Slow blinking red LED'"
configuring  --->  s31 : timeout b'2:00' / b"echo('Exit configuring mode');"

@enduml
