@startuml

state idle
state active {
	state active_skip_config_entry <<entryPoint>>
	state active_exit <<exitPoint>>
	state reading
}
state error

idle  --->  active : activate
[*]  --->  idle
active_skip_config_entry  --->  reading
idle  --->  active_skip_config_entry : skip configuring
active  --->  idle : deactivate
error  --->  active : reset
idle  --->  [*] : shutoff
active_exit  --->  error

@enduml
