@startuml

state idle
state active {
	state active_skip_config_entry <<entryPoint>>
	state active_exit <<exitPoint>>
	state reading
}
state error

[*]  --->  idle
idle  --->  active_skip_config_entry : skip configuring
idle  --->  [*] : shutoff
active  --->  idle : deactivate
active_skip_config_entry  --->  reading
active_exit  --->  error
idle  --->  active : activate
error  --->  active : reset

@enduml
