@startuml
state active {
    state exitA <<exitPoint>>
    state entry <<entryPoint>>
}
state error
state idle

[*] --> idle
idle -> active : event(call, activate)
idle -> active_skip_config_entry : event(call, 'skip configuring')
active -> idle : event(call, deactivate)
idle --> [*] : event(call, shutoff)
exitA --> error


@enduml
